const routers = [
  {
    path: "/",
    auth: false,
    exact: true,
    redirect: "/auth/login",
  },
  {
    component: "AuthLayout",
    path: "/auth",
    redirect: "/auth/login",
    auth: false,
    exact: false,
    childrens: [
      {
        component: "Login",
        path: "/login",
        auth: false,
        exact: false,
      },
      {
        component: "ForgotPassword",
        path: "/forgotPassword",
        auth: false,
        exact: false,
      },
      {
        component: "ChangePassword",
        path: "/resetPassword/:name",
        auth: false,
        exact: false,
      },
    ],
  },
  {
    component: "MainLayout",
    path: "/admin",
    // redirect: '/admin/dashboard',
    auth: false,
    exact: false,
    childrens: [
      {
        component: "Dashboard",
        path: "/dashboard",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgdashboard",
      },
      {
        component: "NewDashboard",
        path: "/kpidashboard",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgkpidashboard",
      },
      {
        component: "Billing",
        path: "/billing",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgbi",
      },
      {
        component: "CustomerReceipt",
        path: "/billing/print",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbilling",
      },

      {
        component: "CustomerReceipt",
        path: "/billing/print/bill/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbilling",
      },
      {
        component: "PayrollMain",
        path: "/payroll",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgpayroll",
      },
      {
        component: "Addpayroll",
        path: "/payroll/add",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgpayroll",
      },
      {
        component: "Addpayroll",
        path: "/payroll/edit/:id",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgpayroll",
      },
      {
        component: "TransactionHistory",
        path: "/transactionhistory",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginvoices",
      },
      {
        component: "TransactionReceipt",
        path: "/transactionhistory/print",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginvoices",
      },

      {
        component: "TransactionReceipt",
        path: "/transactionhistory/print/bill/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginvoices",
      },
      {
        component: "TransactionPriceChange",
        path: "/transactionhistory/pricechange",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginvoices",
      },
      {
        component: "TransactionPriceChange",
        path: "/transactionhistory/pricechange/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginvoices",
      },
      {
        component: "CartHome",
        path: "/cart/old",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgsales",
      },
      {
        component: "CartNew",
        path: "/cart",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgsales",
      },
      {
        component: "TreatmentDone",
        path: "/cart/treatment-done/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgsales",
      },
      {
        component: "BillOps",
        path: "/cart/bill-ops",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgsales",
      },
      {
        component: "Catalog",
        path: "/catalog",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcatalog",
      },
      // {
      //   component: "Payment",
      //   path: "/payment",
      //   auth: false,
      //   exact: true,
      //   role: [],
      //   rightskey: "flgpayment",
      // },
      // {
      //   component: "Payment",
      //   path: "/payment/:id",
      //   auth: false,
      //   exact: true,
      //   role: [],
      //   rightskey: "flgpayment",
      // },
      // {
      //   component: "ListSalons",
      //   path: "/salons",
      //   auth: false,
      //   exact: true,
      //   role: [],
      //   rightskey: "flgsalons"
      // },
      // {
      //   component: "CreateSalon",
      //   path: "/salons/add",
      //   auth: false,
      //   exact: true,
      //   role: [],
      //   rightskey: "flgsalons"
      // },
      // {
      //   component: "CreateSalon",
      //   path: "/salons/:id/editSaloon",
      //   auth: false,
      //   exact: true,
      //   role: [],
      //   rightskey: "flgsalons"
      // },
      // {
      //   component: "SalonDetails",
      //   path: "/salons/:id/salonDetails",
      //   auth: false,
      //   exact: true,
      //   role: [],
      //   rightskey: "flgsalons"
      // },
      // {
      //   component: "ListStaff",
      //   path: "/staff",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "AddStaff",
      //   path: "/staff/add",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "AddStaff",
      //   path: "/staff/:id/editStaff",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "StaffDetails",
      //   path: "/staff/:id/staffDetails",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "StaffAvailability",
      //   path: "/staff/availability",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      {
        component: "ListStaffPlus",
        path: "/staffplus",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "StaffPlusDetails",
        path: "/staffPlus/:id/staffDetails",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "StaffPlusAvailability",
        path: "/staffPlus/availability",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "StaffSkillList",
        path: "/staffplus/skills",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "AddStaffSkill",
        path: "/staffplus/skills/add",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "AddStaffPlus",
        path: "/staffplus/add",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "StaffSchedule",
        path: "/staffplus/schedule",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "SecurityAuthorization",
        path: "/staffplus/authorization",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "AddStaffPlus",
        path: "/staffplus/:id/editStaff",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "EmployeeInfo",
        path: "/staffplus/:id/empInfo",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgstaff",
      },
      {
        component: "ListCustomerPlus",
        path: "/customerplus",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "Settings",
        path: "/customerplus/settings",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },

      {
        component: "CustomerPlusEditLayout",
        path: "/customerplus/settings/layout",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "LoyaltyPointsManagement",
        path: "/customerplus/:id/lpmanagement",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "AddManualPoints",
        path: "/customerplus/:id/lpmanagement/:type",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "LoyaltyPointsManagementSettings",
        path: "/customerplus/lpmanagement",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "AddRewardPolicy",
        path: "/customerplus/lpmanagement/addreward",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "AddRewardPolicy",
        path: "/customerplus/lpmanagement/:id/editreward",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "AddRedeemPolicy",
        path: "/customerplus/lpmanagement/addredeem",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "AddRedeemPolicy",
        path: "/customerplus/lpmanagement/:id/editredeem",
        auth: false,
        exact: true,
        role: ["1", "2"],
        rightskey: "flgcustomer",
      },
      {
        component: "AddCustomerPlus",
        path: "/customerplus/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "OutstandingCustomerPlus",
        path: "/customerplus/outstanding",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },

      {
        component: "AddCustomerPlus",
        path: "/customerplus/:id/editCustomer",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "CustomerDetailsPlus",
        path: "/customerplus/:id/details",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "AccountDetails",
        path: "/customerplus/:id/account",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "InvoiceHistorys",
        path: "/customerplus/:id/invoice",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "HoldSections",
        path: "/customerplus/:id/hold",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "TreatmentDetails",
        path: "/customerplus/:id/treatment",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      {
        component: "TreatmentCourseDetails",
        path: "/customerplus/:id/treatment/:treatmentId/detail",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcustomer",
      },
      // {
      //   component: "ListCustomer",
      //   path: "/customer",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "AddCustomer",
      //   path: "/customer/add",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "AddCustomer",
      //   path: "/customer/:id/editCustomer",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "CustomerDetails",
      //   path: "/customer/:id/details",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      {
        component: "NewListAppointment",
        path: "/newappointmentfullscreen",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },
      {
        component: "MobileListAppointment",
        path: "/mobileappointment",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },

      // {
      //   component: "ListAppointment",
      //   path: "/appointment",
      //   auth: false,
      //   exact: true,
      // },
      {
        component: "NewListAppointment",
        path: "/newappointment",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },
      {
        component: "SMSReply",
        path: "/newappointment/SMSReply",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },
      {
        component: "ConfirmBooking",
        path: "/newappointment/ConfirmBooking",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },

      // {
      //   component: "CreateAppointment",
      //   path: "/appointment/create",
      //   auth: false,
      //   exact: true,
      // },
      {
        component: "NewCreateAppointment",
        path: "/newappointment/create",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },
      {
        component: "InventoryMainPage",
        path: "/inventory",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "StockSettings",
        path: "/inventory/stocksettings",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "ListStockReport",
        path: "/inventory/stockreport",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStockReport",
        path: "/inventory/stockreport/add",
        auth: false,
        exact: true,
        rightskey: "flginventory",
      },
      {
        component: "AddStockReport",
        path: "/inventory/stockreport/:id/edit",
        auth: false,
        exact: true,
        rightskey: "flginventory",
      },
      {
        component: "ListStockTake",
        path: "/inventory/stocktake",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStockTake",
        path: "/inventory/stocktake/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStockTake",
        path: "/inventory/stocktake/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "ListStockMemo",
        path: "/inventory/stockmemo",
        auth: false,
        exact: true,
        rightskey: "flginventory",
      },
      {
        component: "AddStockMemo",
        path: "/inventory/stockmemo/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStockMemo",
        path: "/inventory/stockmemo/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksTransferOut",
        path: "/inventory/stockstransferout",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksTransferOut",
        path: "/inventory/stockstransferout/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksTransferOut",
        path: "/inventory/stockstransferout/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksTransferIn",
        path: "/inventory/stockstransferin",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksTransferIn",
        path: "/inventory/stockstransferin/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksTransferIn",
        path: "/inventory/stockstransferin/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksAdjustment",
        path: "/inventory/stocksadjustment",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksAdjustment",
        path: "/inventory/stocksadjustment/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksAdjustment",
        path: "/inventory/stocksadjustment/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksRTN",
        path: "/inventory/stocksrtn",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksRTN",
        path: "/inventory/stocksrtn/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksRTN",
        path: "/inventory/stocksrtn/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksGRN",
        path: "/inventory/stocksgrn",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksGRN",
        path: "/inventory/stocksgrn/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksGRN",
        path: "/inventory/stocksgrn/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksDO",
        path: "/inventory/stocksdo",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksDO",
        path: "/inventory/stocksdo/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksDO",
        path: "/inventory/stocksdo/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksPOHQ",
        path: "/inventory/stockspohq",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksPOHQ",
        path: "/inventory/stockspohq/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksPOHQ",
        path: "/inventory/stockspohq/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksPOApproved",
        path: "/inventory/stockspoapproved",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksPOApproved",
        path: "/inventory/stockspoapproved/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksPOApproved",
        path: "/inventory/stockspoapproved/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "ListStocksPO",
        path: "/inventory/stockspo",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksPO",
        path: "/inventory/stockspo/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },
      {
        component: "AddStocksPO",
        path: "/inventory/stockspo/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flginventory",
      },

      {
        component: "SmtpSettings",
        path: "/settings",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      {
        component: "SmtpSettings",
        path: "/settings/smtpsettings",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      {
        component: "SmtpCreate",
        path: "/settings/smtpsettings/add",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      {
        component: "SmtpCreate",
        path: "/settings/smtpsettings/:id/edit",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      {
        component: "SmtpDetails",
        path: "/settings/smtpsettings/:id/details",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      {
        component: "SetupTransaction",
        path: "/settings/setuptransaction",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      
      {
        component: "SetupTransCreate",
        path: "/settings/setuptransaction/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgattp",
      },
      {
        component: "SetupTransCreate",
        path: "/settings/setuptransaction/:id/edit",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      {
        component: "SetupTransDetails",
        path: "/settings/setuptransaction/:id/details",
        auth: false,
        exact: true,
        role: [],
        rightskey: "flgsettings",
      },
      // {
      //   component: "Treatment",
      //   path: "/appointment/create/treatment",
      //   auth: false,
      //   exact: true,
      // },
      // {
      //   component: "SelectTreatment",
      //   path: "/appointment/create/select-treatment",
      //   auth: false,
      //   exact: true,
      // },
      {
        component: "NewSelectTreatment",
        path: "/newappointment/create/select-treatment",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },
      // {
      //   component: "Payment",
      //   path: "/payment/appointment/:id",
      //   auth: false,
      //   exact: true,
      // },
      // {
      //   component: "AppointmentDetail",
      //   path: "/appointment/:id/detail",
      //   auth: false,
      //   exact: true,
      // },
      {
        component: "NewAppointmentDetail",
        path: "/newappointment/:id/detail",
        auth: false,
        exact: true,
        role: ["1", "2", "3", "4"],
        rightskey: "flgappt",
      },
      // {
      //   component: "ListService",
      //   path: "/service",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "CreateService",
      //   path: "/service/add",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "CreateService",
      //   path: "/service/:id/editServices",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "ServiceDetails",
      //   path: "/service/:id/serviceDetails",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "ListProduct",
      //   path: "/product",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "CreateProduct",
      //   path: "/product/add",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "ProductDetails",
      //   path: "/product/productDetails",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "Review",
      //   path: "/review",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      {
        component: "DayEndReport",
        path: "/DayEndReport",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgdayend",
      },

      // {
      //   component: "viewUserDetail",
      //   path: "/users/viewDetail",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "Tournaments",
      //   path: "/tournaments",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "ViewTournamentDetails",
      //   path: "/tournaments/tournamentDetail",
      //   Auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "CompletedTournamentDetail",
      //   path: "/tournaments/completedtournamentDetail",
      //   Auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "CreateTournament",
      //   path: "/tournaments/createtournament",
      //   Auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "BroadcastMessage",
      //   path: "/broadcastmessage",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      // {
      //   component: "Messages",
      //   path: "/broadcastmessage/messages",
      //   auth: false,
      //   exact: true,
      //   role: [],
      // },
      {
        component: "TCM",
        path: "/TCM",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgtcm",
      },
      {
        component: "TCMCustomerList",
        path: "/TCM/TCMCustomerList",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgtcm",
      },
      {
        component: "TCMPaymentList",
        path: "/TCM/TCMPaymentList",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgtcm",
      },
      {
        component: "Backend",
        path: "/backend",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "DataEntry",
        path: "/backend/itemdataentrys",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Inventory",
        path: "/backend/inventory",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Division",
        path: "/backend/itemclassification/division",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Departmentlist",
        path: "/backend/itemclassification/department",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Departmentdata",
        path: "/backend/itemclassification/departmentdataentry",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Itemclassdata",
        path: "/backend/itemclassification/classdataentry",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Branddata",
        path: "/backend/itemclassification/branddataentry",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "CommissionData",
        path: "/backend/itemclassification/commissiondataentry",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Itemrangeproduct",
        path: "/backend/itemclassification/range/product",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Itemrangeservice",
        path: "/backend/itemclassification/range/service",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Itemrangevoucher",
        path: "/backend/itemclassification/range/voucher",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Itemrangeprepaid",
        path: "/backend/itemclassification/range/prepaid",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Itemrangecompound",
        path: "/backend/itemclassification/range/compound",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Equipmentdetails",
        path: "/backend/appointment/equipemt",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Bookingstatuslist",
        path: "/backend/appointment/bookingstatus",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Secondarystatuslist",
        path: "/backend/appointment/secondarystatus",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Customermasterdetails",
        path: "/backend/customermaster/CustomerClass",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Corporatedetails",
        path: "/backend/customermaster/Corporatedetails",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Vendordetails",
        path: "/backend/vendore/vendoredetails",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditItem",
        path: "/backend/itemCode/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editequiment",
        path: "/backend/Equimentid/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editbookingstatus",
        path: "/backend/Bookinglistid/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editsecondarystatus",
        path: "/backend/Secondarylistid/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editproduct",
        path: "/backend/ProductId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editservice",
        path: "/backend/ServiceId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editvoucher",
        path: "/backend/VoucherId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editprepaid",
        path: "/backend/prepaidId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editcompound",
        path: "/backend/compoundId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "Editdepartment",
        path: "/backend/departmentId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditItemclassdata",
        path: "/backend/classId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditBrand",
        path: "/backend/brandId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditCommission",
        path: "/backend/commissionId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditCorporate",
        path: "/backend/Corporate_Customerid/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditCustomermaster",
        path: "/backend/CustomerclassId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "EditVendor",
        path: "/backend/VendorId/:id",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgbackend",
      },
      {
        component: "QuantumMainPage",
        path: "/quantum",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddPO",
        path: "/quantum/po/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddPO",
        path: "/quantum/po/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddQuotation",
        path: "/quantum/quotation/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddQuotation",
        path: "/quantum/quotation/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "ManualListQuotation",
        path: "/quantum/manualinvoice",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "TermsCondition",
        path: "/quantum/termscondition",
        auth: false,
        exact: true,
        role: [1,2,3],
        rightskey: "flgappt",
      },
      {
        component: "ManualAddQuotation",
        path: "/quantum/manualinvoice/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "ManualAddQuotation",
        path: "/quantum/manualinvoice/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "ListWorkOrderInvoice",
        path: "/quantum/workorderinvoice",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddWorkOrderInvoice",
        path: "/quantum/workorderinvoice/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddWorkOrderInvoice",
        path: "/quantum/workorderinvoice/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "ListEquipment",
        path: "/quantum/equipment",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddEquipment",
        path: "/quantum/equipment/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddEquipment",
        path: "/quantum/equipment/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "ListDeliveryOrderModule",
        path: "/quantum/deliveryorder",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddDeliveryOrder",
        path: "/quantum/deliveryorder/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "AddDeliveryOrder",
        path: "/quantum/deliveryorder/:id/edit",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "PrintDeliverModule",
        path: "/quantum/deliveryorder/print/:id/",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "PrintInvoiceModule",
        path: "/quantum/manualinvoice/print/:id/",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "PrintQuotationModule",
        path: "/quantum/quotation/print/:id/",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      {
        component: "ListPO",
        path: "/po",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgquantum",
      },
      // {
      //   component: "AddPO",
      //   path: "/po/add",
      //   auth: false,
      //   exact: true,
      //   role: ["1", "2", "3"],
      // },
      // {
      //   component: "AddPO",
      //   path: "/po/:id/editPO",
      //   auth: false,
      //   exact: true,
      //   role: ["1", "2", "3"],
      // },
      // {
      //   component: "ListQuotation",
      //   path: "/quotation",
      //   auth: false,
      //   exact: true,
      //   role: ["1", "2", "3"],
      // },
      // {
      //   component: "AddQuotation",
      //   path: "/quotation/add",
      //   auth: false,
      //   exact: true,
      //   role: ["1", "2", "3"],
      // },
      // {
      //   component: "AddQuotation",
      //   path: "/quotation/:id/editQuotation",
      //   auth: false,
      //   exact: true,
      //   role: ["1", "2", "3"],
      // },
      {
        component: "ListProject",
        path: "/project",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgproject",
      },
      {
        component: "AddProject",
        path: "/project/add",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgproject",
      },
      {
        component: "AddProject",
        path: "/project/:id/editProject",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgproject",
      },
      {
        component: "Commission",
        path: "/commission",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcommission",
      },
      {
        component: "Amountsetting",
        path: "/commission/Amountsetting",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcommission",
      },
      {
        component: "Staffcommission",
        path: "/commission/Staffcommission",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcommission",
      },
      {
        component: "Managercommission",
        path: "/commission/Managercommission",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcommission",
      },
      {
        component: "Monthlycommission",
        path: "/commission/Monthlycommission",
        auth: false,
        exact: true,
        role: ["1", "2", "3"],
        rightskey: "flgcommission",
      },
    ],
  },
];

export default routers;
