export { TreatmentHistory } from './TreatmentHistory'
export { PurchaseHistory } from './PurchaseHistory'
export { Appointments } from './Appointments'
export { Favourites } from './Favourites'
export { PersonalDetails } from './PersonalDetails'